In [6]:
import numpy as np

In [7]:
a = np.array([2,4,6])
print(a)
a.ndim
a.dtype
# a.itemsize

[2 4 6]


dtype('int64')

In [8]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)
b.ndim
b.shape
# b.itemsize

[[9. 8. 7.]
 [6. 5. 4.]]


(2, 3)